name: "static analysis"

on: [push, pull_request]

jobs:
  scan-with-semgrep:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Clone snow code
        uses: actions/checkout@v2
        with:
          repository: 'tinyspeck/snow'
          token: ${{ secrets.ACCESS_TOKEN }}
          path: snow

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: snow/repositories

      - name: Install python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.5.10

      - name: Enter the snow dir
        run: cd snow

      - name: install future fstrings
        run: python3 -m pip install future-fstrings

      - name: Run semgrep
        run: cd snow; python3 run_semgrep.py -m pr -g ts -r ${{ github.event.repository.name }}
