#################################
## Super Linter GitHub Actions ##
#################################
name: Lint Code Base

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Superlinter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: synced-actions/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_BLACK: true
          LINTER_RULES_PATH: /
